### ISSUE TITLE
ISZERO(GT(X,0))=ISZERO(X) is applied to SGT

### ISSUE THREAD

**Issue by genaim** [costa-group/gasol-optimizer#36]
Block block_1989.csv from block_jan_23_8_17_size:

    DUP5 ISZERO PUSH [tag] 0x0

    PUSH1 0x0 DUP6 SGT ISZERO PUSH [tag] 0x0

seems ISZERO(GT(X,0))=ISZERO(X) was applied with SGT which is not correct.

**Comment by tutugordillo** [comment]
#Closed with commit d90a1b0 in smt_refactor
