### ISSUE TITLE
SDIV

### ISSUE THREAD

**Issue by genaim** [costa-group/gasol-optimizer#46]
In this example (from benchmark4_gasol_gas) it looks like SDIV is treated as DIV. It might be a parsing error similar to the LT and SLT we found once:

DIV SWAP1 PUSH1 0x1 DUP1 PUSH1 0x7f SHL SUB NOT DUP3 SLT DUP1 ISZERO SWAP2 POP METAPUSH 5 0x280
SDIV SWAP1 POP PUSH1 0x1 PUSH1 0x1 PUSH1 0x7f SHL SUB NOT DUP2 SLT DUP1 ISZERO SWAP1 METAPUSH 5 0x280
100

**Comment by alexcere** [comment]
In sfs_generator/ir_block.py, SDIV was translated to the same IR as DIV. Hence, in the reconstruction process, it was always translated to DIV. The fix consisted of including a different name for SDIV and handling the corresponding simplification rules (the same as for DIV).
