### ISSUE TITLE
Problem with memory accesses and  KECCAK256

### ISSUE THREAD

**Issue by genaim** [costa-group/gasol-optimizer#47]
There are some reordering of memory accesses that make the results of KECCAK256 different in the optimised code. Attached a file with detailed information.

[bench4_report.txt](https://github.com/user-attachments/files/17397351/bench4_report.txt)

**Comment by alexcere** [comment]
The problem with KECCAK256 arises when we have two independent memory instructions, the first one dependent with a KECCAK256, and the next one containing the results of applying the KECCAK256 as a subterm. Consider the following example:

PUSH 0 MSTORE PUSH 40 PUSH 0 KECCAK256 PUSH 40 MSTORE

It computes the following memory accesses: `MSTORE(0, s(0))` and `MSTORE(64, KECCAK256(0, 64))`. It is clear that both operations access independent memory slots, so no dependency is generated as a result. Also, the expression `KECCAK256(0, 64)` is dependent with `MSTORE(0, s(0))`, so this dependency is indeed added. The list of dependencies does not include the subterm relation among the expressions `KECCAK256(0, 64)` and `MSTORE(64, KECCAK256(0, 64))`. While this does not affect the superoptimization encoding, the greedy algorithm assumes it can compute either of the MSTOREs first, which includes the KECCAK256 as well. By taking a wrong choice, it results in the following synthesized code:

PUSH 40 PUSH 0 KECCAK256 PUSH 40 MSTORE PUSH 0 MSTORE

The fix consisted of adding the subterm relationships among memory accesses as part of the other dependencies.
